TicTacToe:
  class_name: "AlphaZeroTicTacToeAgent"
  pretrained: "az_tictactoe_500_100.pt" 
  settings:
    search_time: 1
    exploration_rate: 1.0     
  train:
    params:
      num_iterations: 10
      num_games: 50
      num_simulations: 100
      buffer_size: 3000
      temperature: [1.0, 3, 0.01]
      noise: [0.25, 0.5]
      learning_rate: [0.005, [5], 0.1]
      weight_decay: 0.0001
      batch_size: 64

ConnectFour:
  class_name: "AlphaZeroConnectFourAgent"
  pretrained: "az_connectfour_1000_200.pt" 
  settings:
      search_time: 3
      exploration_rate: 1.0     
  train:
    params:
      num_iterations: 10
      num_games: 100
      num_simulations: 200
      buffer_size: 10000
      temperature: [1.0, 10, 0.01]
      noise: [0.25, 0.5]
      learning_rate: [0.005, [5], 0.1]
      weight_decay: 0.0001
      batch_size: 256